language: 
  - generic

os:
  - linux

dist:
  - xenial

services:
  - docker

before_install:
  - docker build -t trebu2002/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true trebu2002/react-test npm test

after_success:
  - docker build -t trebu2002/multi-client ./client
  - docker build -t trebu2002/multi-server ./server
  - docker build -t trebu2002/multi-worker ./worker
  - docker build -t trebu2002/mutli-nginx ./nginx

# Log into Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# Take images and push them to the Docker Hub
  - docker push trebu2020/multi-client
  - docker push trebu2020/mutli-server
  - docker push trebu2020/multi-worker
  - docker push trebu2020/multi-nginx
