language: 
  - generic

os:
  - linux

dist:
  - xenial

services:
  - docker

before_install:
  - docker build -t trebu2020/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true trebu2020/react-test npm test

after_success:
  - docker build -t trebu2020/multi-client ./client
  - docker build -t trebu2020/multi-server ./server
  - docker build -t trebu2020/multi-worker ./worker
  - docker build -t trebu2020/multi-nginx ./nginx

# Log into Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# Take images and push them to the Docker Hub
  - docker push trebu2020/multi-client
  - docker push trebu2020/multi-server
  - docker push trebu2020/multi-worker
  - docker push trebu2020/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-west-2-792648339719'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
